(async()=>{
  if(!new URLSearchParams(location.search).has('test'))return;
  const results=[],out=document.getElementById('results'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const assert=(yes,msg)=>{if(!yes)throw new Error(msg);};
  const test=async(name,fn)=>{try{await fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}out.textContent=results.map(r=>(r.pass?'PASS ':'FAIL ')+r.name+(r.error?' — '+r.error:'')).join('\n');};
  const root=()=>LiltDemo.root,bar=()=>root().querySelector('.bar'),mode=()=>bar().dataset.mode;
  function key(field,key,extra={}){const e=new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...extra});field.dispatchEvent(e);return e;}
  function set(field,value,caret=value.length){if('value'in field)field.value=value;else field.textContent=value;LiltEditor.select(field,caret);field.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:value}));}
  async function prepare(id='email',settings={}){document.querySelectorAll('.pane').forEach(p=>p.hidden=false);const f=document.getElementById(id);f.value!==undefined?f.value='':f.textContent='';LiltDemo.set({enabled:true,source:'en',target:'fr',practice:false,placement:'fixed',...settings});f.focus();await sleep(120);return f;}
  await sleep(200);
  await test('Password and OTP fields are excluded',async()=>{assert(!LiltEditor.eligible(document.getElementById('password')),'password allowed');assert(!LiltEditor.eligible(document.getElementById('otp')),'OTP allowed');});
  await test('Word translation replaces a plain textarea word',async()=>{const f=await prepare();set(f,'hello ');await sleep(100);assert(f.value==='bonjour ','word not replaced: '+f.value);});
  await test('Local suggestions appear while typing without a word model',async()=>{const f=await prepare();const before=LiltDemo.requests.length;set(f,'neigh');assert(mode()==='word','no prefix suggestions');assert(LiltDemo.requests.length===before,'word model was called');});
  await test('Pause automatically inserts a complete sentence',async()=>{const f=await prepare();set(f,'My neighbor is funny. ');await sleep(1250);assert(f.value==='Mon voisin est amusant. ','sentence not adopted: '+f.value);assert(mode()==='review','review missing: '+mode());});
  await test('First Enter sends immediately while a reconstruction is pending',async()=>{const f=await prepare('message');LiltDemo.delay=400;set(f,'My neighbor is funny. ');await sleep(1050);const before=LiltDemo.submissions(),text=f.textContent;key(f,'Enter');assert(LiltDemo.submissions()===before+1,'Enter did not reach the page');await sleep(450);assert(f.textContent===text,'late result changed sent text');LiltDemo.delay=70;});
  await test('Automatic translation keeps the normal submission behavior',async()=>{const f=await prepare('message');set(f,'My neighbor is funny. ');await sleep(1250);assert(f.textContent==='Mon voisin est amusant. ','translation not inserted');const before=LiltDemo.submissions();key(f,'Enter');assert(LiltDemo.submissions()===before+1,'Enter failed to send');});
  await test('Caret return exposes accepted sentence words and definitions',async()=>{const f=document.getElementById('message');LiltEditor.select(f,4);f.dispatchEvent(new MouseEvent('click',{bubbles:true}));await sleep(140);assert(mode()==='review','review missing');const b=root().querySelector('.word');assert(b,'word buttons missing');b.click();await sleep(120);assert(!root().querySelector('.bubble').hidden,'definition bubble missing');});
  await test('Undo restores the previous wording',async()=>{const b=root().querySelector('[aria-label="Restore original text"]');b.click();assert(document.getElementById('message').textContent.includes('My neighbor'),'source not restored');});
  await test('Ambiguous matches wait for a choice; Tab previews meaning and Space commits',async()=>{const f=await prepare();set(f,'bank ');await sleep(150);assert(f.value==='bank ','unreviewed dictionary match auto-committed');key(f,'Tab');assert(!root().querySelector('.bubble').hidden,'meaning missing');key(f,' ');assert(f.value==='rive ','selected candidate not committed: '+f.value);});
  await test('Practice accepts approximate French spelling',async()=>{const f=await prepare('email',{practice:true,target:'fr'});set(f,'bonjoor ');await sleep(150);assert(f.value==='bonjour ','phonetic French failed');});
  await test('Romaji and toneless pinyin produce character candidates',async()=>{let f=await prepare('email',{practice:true,target:'ja'});set(f,'eki ');await sleep(100);assert(f.value==='駅 ','romaji failed');f=await prepare('email',{practice:true,target:'zh'});set(f,'nihao ');await sleep(100);assert(f.value==='你好 ','pinyin failed');});
  await test('Turning translation off restores native typing and Enter',async()=>{const f=await prepare('search',{enabled:false});set(f,'hello ');await sleep(150);assert(f.value==='hello ','disabled extension changed input');assert(!key(f,'Enter').defaultPrevented,'disabled extension intercepted Enter');});
  await test('Rich text edit preserves unrelated formatting',async()=>{const f=document.getElementById('rich');f.innerHTML='<b>Hello</b> world';LiltEditor.replace(f,6,11,'monde');assert(f.querySelector('b')?.textContent==='Hello','formatting lost');assert(f.textContent==='Hello monde','rich text incorrect');});
  await test('Multiline rich-text offset mapping includes paragraphs',async()=>{const f=document.getElementById('rich');f.innerHTML='<div>First</div><div>Second</div>';const map=LiltEditor.linearize(f);assert(map.text==='First\nSecond','paragraph boundary missing: '+map.text);LiltEditor.select(f,8);assert(LiltEditor.read(f).start===8,'caret offset wrong');});
  await test('Floating panel stays inside the viewport',async()=>{const f=await prepare('email',{placement:'floating'});set(f,'hello ');await sleep(150);const r=bar().getBoundingClientRect();assert(r.left>=0&&r.right<=innerWidth+1&&r.top>=0&&r.bottom<=innerHeight+1,'panel clipped');});
  await test('Sentence response after another key is discarded',async()=>{const f=await prepare();LiltDemo.delay=450;set(f,'My neighbor is funny. ');await sleep(1050);key(f,'a');set(f,f.value+'a');const text=f.value;await sleep(550);assert(f.value===text,'stale sentence changed newer typing');LiltDemo.delay=70;});
  const report={browser:navigator.userAgent,total:results.length,passed:results.filter(r=>r.pass).length,results};
  document.title=`Passport QA · ${report.passed}/${report.total} passed`;window.LiltTestReport=report;
  try{await fetch('/__test_results',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(report)});}catch{}
  document.getElementById('qa').open=true;
})();
